### ISSUE TITLE
How can get notification?

### ISSUE THREAD

**Issue by huynhnv** [Sadzeih/push-send-register#1]
Hello you,
When I follow it (push-send-register). I can't run cmd:
ionic push webhook_url http://domain.com/register.php
it error: Unable to find command: push webhook_url, so can you show me how run it.? 
Tks so much

**Comment by Sadzeih** [comment]
Hi,
Sorry to disappoint you but this repo is probably not working with recent ionic versions. This code is 4 years old and don't maintain it to stay current.
If you want to make the modifications, be my guest, but I won't work on this anymore.
